// Mocks generated by Mockito 5.0.7 from annotations
// in dart_authentication_service/test/authentication_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dart_authentication_service/src/authentication_result.dart'
    as _i2;
import 'package:dart_authentication_service/src/providers/cognito_provider.dart'
    as _i3;
import 'package:dart_authentication_service/src/providers/cognito_user.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeAuthenticationResult extends _i1.Fake
    implements _i2.AuthenticationResult {}

/// A class which mocks [CognitoProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCognitoProvider extends _i1.Mock implements _i3.CognitoProvider {
  MockCognitoProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set user(_i4.CognitoUser? _user) =>
      super.noSuchMethod(Invocation.setter(#user, _user),
          returnValueForMissingStub: null);
  @override
  bool isLoggedIn() => (super.noSuchMethod(Invocation.method(#isLoggedIn, []),
      returnValue: false) as bool);
  @override
  _i5.Future<_i2.AuthenticationResult> logIn(
          String? username, String? password) =>
      (super.noSuchMethod(Invocation.method(#logIn, [username, password]),
              returnValue: Future<_i2.AuthenticationResult>.value(
                  _FakeAuthenticationResult()))
          as _i5.Future<_i2.AuthenticationResult>);
}
