name: dart_authentication_service
description: A new Dart package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  amazon_cognito_identity_dart_2: ^1.0.3
  hive: ^2.0.4
  jose: ^0.3.2

dev_dependencies:
  test:
  mockito: ^5.0.2
  build_runner: ^1.11.0
