name: dart_authentication_service
description: A simple flutter package to handle AWS Cognito based authentication and user attributes.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  amplify_auth_cognito: ^0.3.2
  amplify_flutter: ^0.3.2
  hive: ^2.0.5
  jose: ^0.3.2

dev_dependencies:
  test:
  mockito: ^5.0.17
  build_runner: ^2.1.7
